databases:
  - name: todo_machine_backend
    databaseName: todo_machine_backend
    user: todo_machine_backend

services:
  - type: web
    name: TODO_machine_backend
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn TODO_backend.wsgi:application"
    envVars:
    - key: DATABASE_URL
      fromDatabase:
        name: TODO_machine_backend
        property: connectionString
    - key: SECRET_KEY
      generateValue: true
    - key: WEB_CONCURRENCY
      value: 4