# Generated by Django 4.0.6 on 2022-08-29 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_workspace_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(default='Default User', max_length=255),
        ),
    ]
